### ISSUE TITLE
Conclusion: remove pulkitjalan/geoip dev-master

### ISSUE THREAD

**Issue by canfiax** [pulkitjalan/geoip#11]
I am getting the following error when running `composer update` in my project now:

Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - Conclusion: remove pulkitjalan/geoip dev-master
        - Conclusion: remove guzzlehttp/guzzle 6.1.1
        - Conclusion: don't install guzzlehttp/guzzle 5.3.0
        - Conclusion: don't install guzzlehttp/guzzle 6.1.1
        - Installation request for pulkitjalan/geoip dev-master -> satisfiable by pulkitjalan/geoip[dev-master].
        - Installation request for tuurbo/spreedly ~1.5.0 -> satisfiable by tuurbo/spreedly[1.5.0].
        - pulkitjalan/geoip dev-master requires guzzlehttp/guzzle ~6 -> satisfiable by guzzlehttp/guzzle[6.1.1, 6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.x-dev].
        - Can only install one of: guzzlehttp/guzzle[6.0.0, 5.2.0].
        - Can only install one of: guzzlehttp/guzzle[6.0.1, 5.2.0].
        - Can only install one of: guzzlehttp/guzzle[6.0.2, 5.2.0].
        - Can only install one of: guzzlehttp/guzzle[6.1.0, 5.2.0].
        - Can only install one of: guzzlehttp/guzzle[6.1.x-dev, 5.2.0].
        - tuurbo/spreedly 1.5.0 requires guzzlehttp/guzzle ~5.2 -> satisfiable by guzzlehttp/guzzle[5.2.0, 5.3.0, 5.3.x-dev].
        - Conclusion: don't install guzzlehttp/guzzle 5.3.x-dev

It used to work fine before.

Why?

**Comment by pulkitjalan** [comment]
`tuurbo/spreedly` uses `guzzle` 5 whereas this package uses guzzle 6. Thats your conflict. might be best to fork either this one or `tuurbo/spreedly` and use the same versions of guzzle.
