### ISSUE TITLE
config_path() undefined

### ISSUE THREAD

**Issue by AndreasHeiberg** [pulkitjalan/geoip#12]
Run:

```php artisan vendor:publish --provider="PulkitJalan\GeoIP\GeoIPServiceProvider" --tag="config"```

Error:

```Call to undefined function PulkitJalan\GeoIP\config_path()```

In GeoIPServiceProvider.

**Comment by AndreasHeiberg** [comment]
This is an error caused by using lumen. config_path does not seem to be available.

**Comment by AndreasHeiberg** [comment]
Solution 1:

Do a check in your service provider if you wanna support Lumen:

```
if (function_exists('config_path')) {
    $this->publishes([
            __DIR__.'/config/config.php' => config_path('geoip.php'),
     ], 'config');
}
```

Solution 2:

I created ```app/Support/Helpers.php``` and added:

```
<?php

if (! function_exists('config_path')) {
    /**
     * Get the configuration path.
     *
     * @param  string $path
     * @return string
     */
    function config_path($path = '')
    {
        return app()->basePath() . '/config' . ($path ? '/' . $path : $path);
    }
}
```

And loaded that in composer.json:

```
{
    "autoload": {
        "files": [
            "app/Support/Helpers.php"
        ]
    },
}
```

**Comment by AndreasHeiberg** [comment]
As for using the package with lumen you have to uncomment "// $app->withFacades();" and add class_alias(\PulkitJalan\GeoIP\Facades\GeoIP::class, 'GeoIP');

**Comment by pulkitjalan** [comment]
This package is not currently compatible with Lumen, I think `solution 1` is probably best to make it compatible. If you can submit a PR I'll have a look and merge it. Thanks
