### ISSUE TITLE
Lat & Lng being returned with comma when on different locale

### ISSUE THREAD

**Issue by simplenotezy** [pulkitjalan/geoip#14]
I have just installed Localization support for my laravel 5 app, using the following two packages:

- https://github.com/mcamara/laravel-localization
- https://github.com/xinax/laravel-gettext

However, when I am on the danish language (which have thousandseperators as comma), lat & lng are being returned as:

    55,6759

Instead of (on the default locale, english):

    55.6759,0

This causes some SQL queries to fail.

Any ideas why? I assume the packages uses the native php function `setlocale` as well.

**Comment by canfiax** [comment]
I am using the telize driver and I notice this response originates all the way back from Telize. For some reason, guzzle must be sending some locale information that Telize respects, and then converts the lat/lng. Is there some way I can force telize/guzzle to return data in a specific locale?

**Comment by canfiax** [comment]
Inside the TelizeDriver, something like this would work, but it seems like a hack, and there should be another way to get around it:



    /**
     * Get array of data using telize.
     *
     * @param string $ip
     *
     * @return array
     */
    public function get($ip)
    {
        $data = $this->getRaw($ip);

        if (empty($data)) {
            return $this->getDefault();
        }

        return [
            'city' => array_get($data, 'city'),
            'country' => array_get($data, 'country'),
            'countryCode' => array_get($data, 'country_code'),
            'latitude' => (float)number_format(array_get($data, 'latitude'), 5),
            'longitude' => (float)number_format(array_get($data, 'longitude'), 5),
            'region' => array_get($data, 'region'),
            'regionCode' => array_get($data, 'region_code'),
            'timezone' => array_get($data, 'timezone'),
            'postalCode' => array_get($data, 'postal_code'),
        ];
    }

**Comment by pulkitjalan** [comment]
Sorry for the delay, i tried to replicate this but its working fine for me.
Does it still happen on the latest version (2.3.1)?

**Comment by pulkitjalan** [comment]
Ive added the above suggestions to the latest version.
