### ISSUE TITLE
rand() expects parameter 2 to be integer, string given

### ISSUE THREAD

**Issue by andreasba** [pulkitjalan/geoip#17]
Hi there

very strange thing. I set up a new XAMMP and ran my application. Now when I run
`$geoIp =  GeoIP::getCountryCode();`
 I receive the following error

**rand() expects parameter 2 to be integer, string given in [...]\pulkitjalan\geoip\src\GeoIP.php:76**
```
/**
     * Get ip from server info.
     *
     * @return string ipaddress
     */
    public function getIp()
    {
        if (! $this->ip) {
            if ($this->random) {
                $this->ip = long2ip(rand(0, '4294967295'));   <<<<<<---- ERROR
            } else {
                $this->ip = array_get($_SERVER, 'HTTP_CLIENT_IP', array_get($_SERVER, 'HTTP_X_FORWARDED_FOR', array_get($_SERVER, 'HTTP_X_FORWARDED', array_get($_SERVER, 'HTTP_FORWARDED_FOR', array_get($_SERVER, 'HTTP_FORWARDED', array_get($_SERVER, 'REMOTE_ADDR', '127.0.0.1'))))));
            }
        }
```

If I change the marked line from long2ip(rand(0, '4294967295')); to long2ip(rand(0, 4294967295)); I get an error about the type being float not integer. If I then change it to long2ip(rand(0, 429496)); it works.

Now on my production system this works, only on my local machine not. But I have not upgraded this package in the last days, so this makes me wondering if this is now somehow broken?

Can anyone confirm this behaviour?

**Comment by pulkitjalan** [comment]
fixed in version 2.3.0

**Comment by andreasba** [comment]
Thanks for the quick fix @pulkitjalan - however, now I get a 

` in GeoIP.php line 77
at HandleExceptions->handleError('2', 'mt_rand() expects parameter 2 to be integer, float given',`

error message :)

**Comment by pulkitjalan** [comment]
Not sure why u are getting this issue, i cant replicate it. what version of php are u using?

ive pushed version 2.3.1, give that a try. Removed `min` and `max` from `mt_rand()`

**Comment by andreasba** [comment]
Hi @pulkitjalan - thanks for your super quick reply and update!

Not it works without an error message. I am using PHP 7.0.8

**Comment by pulkitjalan** [comment]
Cool, strange travis did not catch the issue...
