### ISSUE TITLE
geoip .dat file maxmind

### ISSUE THREAD

**Issue by 4val0v** [pulkitjalan/geoip#20]
Whether support. dat files from maxmind?

**Comment by pulkitjalan** [comment]
The `.dat` files seem to be from [maxmind geoip legacy](http://dev.maxmind.com/geoip/legacy/geolite/), this package uses [maxmind geoip2](http://dev.maxmind.com/geoip/geoip2/geolite2/) which uses `.mmdb`.

Please correct me if I am wrong, but if `.dat` is only for legacy then unfortunately it won't be supported.
