### ISSUE TITLE
Failed to get geoip data

### ISSUE THREAD

**Issue by mooseh** [pulkitjalan/geoip#22]
Hi There, im not sure why but when i add our maxmind credentials to my env file i get the following error

"Failed to get geoip data" followed by
"Your user ID or license key could not be authenticated."

We know this is an active account as we're using it all the time on our old platform.

although we are not using lookups to maxmind but using our credentials to grab the latest database could that be it?

**Comment by mooseh** [comment]
So it is definitely the reason i named above, how can i have the credentials for downloading the latest database with our account but it not use those credentials when trying to lookup an IP?

Thanks

**Comment by pulkitjalan** [comment]
The updater currently does not use the credentials for downloading the database. Have you set a different download url?

the default is `http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz` which is free and does not require credentials.

**Comment by pulkitjalan** [comment]
Is this `https://github.com/maxmind/geoipupdate` what you are using?

If so, you need to follow the instructions on here: `http://dev.maxmind.com/geoip/geoipupdate/#Step_3_8211_Run_GeoIP_Update`.
