### ISSUE TITLE
[Symfony\Component\Debug\Exception\FatalThrowableError] 

### ISSUE THREAD

**Issue by J-Ibarra** [pulkitjalan/geoip#23]
php artisan vendor:publish --provider="PulkitJalan\GeoIP\GeoIPServiceProvider" --tag="config"

[Symfony\Component\Debug\Exception\FatalThrowableError]              
  Call to undefined method Illuminate\Foundation\Application::share()

bindShared has been renamed to $app->singleton()

**Comment by pulkitjalan** [comment]
What version of Laravel are you using?

**Comment by J-Ibarra** [comment]
5.4

**Comment by pulkitjalan** [comment]
The latest version should fix this issue
