### ISSUE TITLE
Use of undefined constant GEOIP_DRIVER - assumed 'GEOIP_DRIVER'

### ISSUE THREAD

**Issue by marcin-derlukiewicz** [pulkitjalan/geoip#3]
[2015-06-11 09:22:32] local.ERROR: exception 'ErrorException' with message 'Use of undefined constant GEOIP_DRIVER - assumed 'GEOIP_DRIVER'' in C:\Users\Marcin\Documents\NetBeansProjects\displate\vendor\pulkitjalan\geoip\src\config\config.php:12
Stack trace:
#0 C:\Users\Marcin\Documents\NetBeansProjects\displate\vendor\pulkitjalan\geoip\src\config\config.php(12): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Use of undefine...', 'C:\\Users\\Marcin...', 12, Array)
#1 C:\Users\Marcin\Documents\NetBeansProjects\displate\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php(66): require('C:\\Users\\Marcin...')
#2 C:\Users\Marcin\Documents\NetBeansProjects\displate\vendor\pulkitjalan\geoip\src\GeoIPServiceProvider.php(38): Illuminate\Support\ServiceProvider->mergeConfigFrom('C:\\Users\\Marcin...', 'geoip')
#3 C:\Users\Marcin\Documents\NetBeansProjects\displate\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(499): PulkitJalan\GeoIP\GeoIPServiceProvider->register()
#4 C:\Users\Marcin\Documents\NetBeansProjects\displate\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php(74): Illuminate\Foundation\Application->register(Object(PulkitJalan\GeoIP\GeoIPServiceProvider))
#5 C:\Users\Marcin\Documents\NetBeansProjects\displate\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(475): Illuminate\Foundation\ProviderRepository->load(Array)
#6 C:\Users\Marcin\Documents\NetBeansProjects\displate\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#7 C:\Users\Marcin\Documents\NetBeansProjects\displate\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(194): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#8 C:\Users\Marcin\Documents\NetBeansProjects\displate\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(192): Illuminate\Foundation\Application->bootstrapWith(Array)
#9 C:\Users\Marcin\Documents\NetBeansProjects\displate\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(92): Illuminate\Foundation\Console\Kernel->bootstrap()
#10 C:\Users\Marcin\Documents\NetBeansProjects\displate\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 {main}

**Comment by pulkitjalan** [comment]
fixed
