### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by zyxxyzyxz** [pulkitjalan/geoip#37]
Laravel 8 uses Guzzle 7 by default. The Guzzle 6 requirement causes a collision.

**Comment by r0bdiabl0** [comment]
Yes, please add support for Laravel 8 and Guzzle 7. Thanks.

**Comment by r0bdiabl0** [comment]
Any movement on this yet?

**Comment by pulkitjalan** [comment]
Tagged version 5
