### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by code2prog** [pulkitjalan/geoip#41]
On PHP 8.0 one of the tests fails (test_ipstack_exception_getRaw). Unfortunately, I was unable to determine the source of the problem

`Failed asserting that exception of type "PulkitJalan\GeoIP\Exceptions\GeoIPException" is thrown.`

**Comment by code2prog** [comment]
I think I found the reason :)
Client error: `GET https://pro.ip-api.com/json/81.2.69.160?lang=en&key=test` resulted in a `403 Forbidden` response:
{"status":"fail","message":"invalid/expired key, renew at https://members.ip-api.com/order"}

**Comment by code2prog** [comment]
@pulkitjalan https://github.com/pulkitjalan/geoip/pull/42
This was the reason for the failure of the tests

**Comment by pulkitjalan** [comment]
Thanks! Merged and released.

**Comment by code2prog** [comment]
@pulkitjalan php dependencies in composer.json should be changed  https://github.com/pulkitjalan/geoip/pull/43
