### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by ajsheldon93** [pulkitjalan/geoip#49]
Can this be updated to allow Laravel 9 support? Currently getting this when tried to install:

```
Problem 1
    - Root composer.json requires pulkitjalan/geoip ^5.1 -> satisfiable by pulkitjalan/geoip[5.1.0].
    - pulkitjalan/geoip 5.1.0 requires illuminate/support ^5.8|^6|^7|^8 -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
```

**Comment by heychazza** [comment]
> Can this be updated to allow Laravel 9 support? Currently getting this when tried to install:
> 
> ```
> Problem 1
>     - Root composer.json requires pulkitjalan/geoip ^5.1 -> satisfiable by pulkitjalan/geoip[5.1.0].
>     - pulkitjalan/geoip 5.1.0 requires illuminate/support ^5.8|^6|^7|^8 -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
> ```

Wondering the same..

**Comment by darthsoup** [comment]
Created a merge request

Ping to @pulkitjalan, so he can merge it
