### ISSUE TITLE
Library not work with laravel 11 

### ISSUE THREAD

**Issue by IsraelCastro997** [pulkitjalan/geoip#59]
Library not work with laravel 11, because require illuminate/support 10 and laravel 11 work illuminate support 11 version

  Problem 1
    - Root composer.json requires pulkitjalan/geoip ^6.0 -> satisfiable by pulkitjalan/geoip[6.0.0].
    - pulkitjalan/geoip 6.0.0 requires illuminate/support ^9|^10.0 -> found illuminate/support[v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.2] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require pulkitjalan/geoip:*" to figure out if any version is installable, or "composer require pulkitjalan/geoip:^2.1" if you know which you need.

**Comment by ahmadabuaysheh** [comment]
Added a PR here: https://github.com/pulkitjalan/geoip/pull/60

**Comment by pulkitjalan** [comment]
Merged
