### ISSUE TITLE
config is ignored

### ISSUE THREAD

**Issue by marcin-derlukiewicz** [pulkitjalan/geoip#6]
after recent updates config file is ignored and everything tries to connect to ip-api

**Comment by pulkitjalan** [comment]
which version are you using?

**Comment by marcin-derlukiewicz** [comment]
@dev
27 sie 2015 17:26 "Pulkit Jalan" <notifications@github.com> napisał(a):

**Comment by pulkitjalan** [comment]
can you try again with the latest version, I am unable to replace this issue.

**Comment by kyranb** [comment]
I'm experiencing this with `dev-master`. 

`$config` in the constructor here: https://github.com/pulkitjalan/geoip/blob/master/src/GeoIP.php#L39

Only contains: [ "driver" => "ip-api"]

It seems as though `config('geoip')` can't be accessed inside of this anonymous function in the GeoIpServiceProvider:

```php
protected function registerGeoIP()
    {
        $this->app['geoip'] = $this->app->share(function ($app) {
            return new GeoIP(config('geoip'));
        });
    }
```
