### ISSUE TITLE
Get asnum and isp name using maxmind driver

### ISSUE THREAD

**Issue by 06chaynes** [pulkitjalan/geoip#8]
Are you currently able to get the asnum and isp name using the maxmind driver? If not do you intend on adding this ability any time soon?

**Comment by pulkitjalan** [comment]
It's not currently supported, and I don't intend to add it anytime soon.

**Comment by pulkitjalan** [comment]
I have added a `getRaw` function in the latest version. You should be able to use it to get the data u need.

**Comment by 06chaynes** [comment]
I will check into that new function, thanks for your acknowledgement on this.
